name: Publish
on:
  push:
    tags:
      - '*'
  workflow_dispatch:
  
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Fetch tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - uses: actions/setup-java@v5
        with:
          java-version: 11
          distribution: 'temurin'
      - name: Publish
        run: ./gradlew build publishPlugins -Pgradle.publish.key=${{secrets.GRADLE_PUBLISH_KEY}} -Pgradle.publish.secret=${{secrets.GRADLE_PUBLISH_SECRET}}
