name: Publish
on:
  push:
    tags:
      - '*'
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Fetch tags
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Publish
        run: ./gradlew build publishPlugins -Pgradle.publish.key=${{secrets.PLUGIN_PORTAL_KEY}} -Pgradle.publish.secret=${{secrets.PLUGIN_PORTAL_SECRET}}
